import type { Metadata } from "next";
import { cn } from "@/lib/utils";
import Header from "@/components/layout/header.layout";
import Footer from "@/components/layout/footer.layout";
import Interactive from "@/components/layout/interactive.layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className={cn("w-full")}>
      <Header />
      <Interactive />
      {children}
      <Footer />
    </main>
  );
}
