import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ReactQueryProvider from "@/react-query.provider";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import AOSProvider from "./aos.provider";
import Script from "next/script";
import "@/styles/index.css";
import "ckeditor5/ckeditor5.css";
import "ckeditor5-premium-features/ckeditor5-premium-features.css";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryProvider>
        <body
          className={cn("min-h-screen font-sans antialiased", poppins.variable)}
        >
          <AOSProvider>{children}</AOSProvider>
          <Toaster position="bottom-center" expand={true} richColors />
        </body>
      </ReactQueryProvider>
    </html>
  );
}
